# Generated by Django 3.1.7 on 2021-04-24 16:44

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('watering', models.CharField(max_length=100)),
                ('sunlight', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
