# Generated by Django 3.1.7 on 2021-04-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210427_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
