# Generated by Django 3.1.7 on 2021-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210427_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='reviews',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
