# Generated by Django 3.1.7 on 2021-05-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_plant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='rating',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
